In [2]:
import sys
from pathlib import Path

import pandas as pd

ROOT = Path.cwd().resolve()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import load_data

In [4]:
df_issue_assignees = load_data.load_issue_assignees()
df_issue_comments = load_data.load_issue_comments()
df_lables = load_data.load_issue_labels()
df_issues = load_data.load_issues()

In [6]:
df_issues.head(2)

,issue_id,repo_name,issue_number,title,body,state_final,author_login,agent_type,n_gharchive_events,comments_count_reported,...,reactions_laugh,reactions_hooray,reactions_confused,reactions_heart,reactions_rocket,reactions_eyes,n_labels,n_assignees,labels,n_comments_actual
0,01capitain/jira-release-manager#66,01capitain/jira-release-manager,66,Add pre-commit hooks for eslint and schema val...,## Problem\n\nSchema validation rules (like th...,open,coderabbitai[bot],CodeRabbit,1,NaN,...,0,0,0,0,0,0,0,1,NaN,0
1,01capitain/jira-release-manager#67,01capitain/jira-release-manager,67,Add Next.js Link component guideline to UI doc...,"## Context\n\nBased on discussion in PR #64, w...",open,coderabbitai[bot],CodeRabbit,1,NaN,...,0,0,0,0,0,0,0,1,NaN,0

In [7]:
df_issues.columns

Index(['issue_id', 'repo_name', 'issue_number', 'title', 'body', 'state_final',
       'author_login', 'agent_type', 'n_gharchive_events',
       'comments_count_reported', 'created_at', 'closed_at',
       'time_to_close_hours', 'html_url', 'api_state', 'state_reason',
       'locked', 'draft', 'is_pull_request', 'author_type', 'api_created_at',
       'api_updated_at', 'api_closed_at', 'comments_api', 'milestone_title',
       'milestone_state', 'reactions_total', 'reactions_plus_one',
       'reactions_minus_one', 'reactions_laugh', 'reactions_hooray',
       'reactions_confused', 'reactions_heart', 'reactions_rocket',
       'reactions_eyes', 'n_labels', 'n_assignees', 'labels',
       'n_comments_actual'],
      dtype='str')

In [24]:
df_issues['api_state'].value_counts(dropna=False)

api_state
closed    3309
open      1691
Name: count, dtype: int64

In [32]:
df_issues[df_issues['state_final'] != df_issues['api_state']].shape

(1959, 41)

In [21]:
df_issues[['issue_id', 'api_state', 'state_reason']]

                                    issue_id api_state state_reason
0         01capitain/jira-release-manager#66    closed    completed
1         01capitain/jira-release-manager#67    closed    completed
2                  01fe23bcs183/indietix#102    closed    completed
3                   01fe23bcs183/indietix#92      open          NaN
4                   01fe23bcs183/indietix#94      open          NaN
...                                      ...       ...          ...
4995  liberu-genealogy/genealogy-laravel#767    closed    completed
4996        JokerTrickster/board_game_app#28      open          NaN
4997          davideast/jules-sdk-python#249    closed    completed
4998       aws/aws-toolkit-visual-studio#596      open          NaN
4999                        slopus/happy#165      open          NaN

[5000 rows x 3 columns]

In [8]:
df_issues.agent_type.value_counts()

agent_type
CodeRabbit            1960
Claude_Code            880
Sweep                  696
Devin                  547
SWE_agent              310
Gemini_Code_Assist     257
Amazon_Q               108
Aider                   68
Kiro                    64
PR_Agent                55
Jules                   49
Copilot                  3
Cursor                   3
Name: count, dtype: int64

In [9]:
df_issues.shape

(5000, 39)

In [11]:
df_issues['author_login']

0               coderabbitai[bot]
1               coderabbitai[bot]
2       devin-ai-integration[bot]
3       devin-ai-integration[bot]
4       devin-ai-integration[bot]
                  ...
4995               curtisdelicata
4996               JokerTrickster
4997                    davideast
4998            sanket27sonukadam
4999                     jeffjose
Name: author_login, Length: 5000, dtype: str

In [27]:
df_issues['title_length'] = df_issues['title'].str.len()

In [28]:
df_issues.groupby('author_type')['title_length'].mean()

author_type
Bot     55.920573
User    54.048591
Name: title_length, dtype: float64

In [29]:
df_issues['body_length'] = df_issues['body'].str.len()

In [31]:
df_issues.groupby('author_type')['body_length'].mean()

author_type
Bot     1660.903604
User    3239.058022
Name: body_length, dtype: float64

In [33]:
df_issues.groupby('author_type')['time_to_close_hours'].mean()

author_type
Bot     0.0
User    0.0
Name: time_to_close_hours, dtype: float64

In [34]:
df_issues['time_to_close_hours'].describe()

count    1307.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: time_to_close_hours, dtype: float64

In [36]:
df_issues['time_to_close_hours'].value_counts(dropna=False)

time_to_close_hours
NaN    3693
0.0    1307
Name: count, dtype: int64

In [ ]:
df_issues['time_to_close_hours']

In [40]:
(df_issues['closed_at'] - df_issues['created_at']).dt.seconds.describe()

count    1307.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
dtype: float64

In [42]:
df_issues[df_issues['closed_at'].isnull()==False][['issue_id','closed_at', 'created_at']]

,issue_id,closed_at,created_at
2,01fe23bcs183/indietix#102,2025-11-03 12:43:09+00:00,2025-11-03 12:43:09+00:00
5,094459/aqd-workshop#2,2025-03-04 07:15:23+00:00,2025-03-04 07:15:23+00:00
6,0x7o/SimpleBlogSite#2,2024-05-30 07:43:32+00:00,2024-05-30 07:43:32+00:00
8,0xHoneyJar/loa#198,2026-02-05 13:13:55+00:00,2026-02-05 13:13:55+00:00
22,2hanbyeol1/searchright-blog#2,2024-12-10 12:43:39+00:00,2024-12-10 12:43:39+00:00
...,...,...,...
4984,rjwalters/vibesql#1247,2025-11-11 02:23:53+00:00,2025-11-11 02:23:53+00:00
4986,yykamei/block-merge-based-on-time#2435,2025-07-08 08:07:45+00:00,2025-07-08 08:07:45+00:00
4991,stevenson-space/shs#398,2026-02-27 20:51:07+00:00,2026-02-27 20:51:07+00:00
4994,anthropics/claude-code#617,2025-03-25 17:53:16+00:00,2025-03-25 17:53:16+00:00
4995,liberu-genealogy/genealogy-laravel#767,2024-06-08 19:28:27+00:00,2024-06-08 19:28:27+00:00

In [12]:
df_issues[df_issues['author_login'] == 'curtisdelicata']

,issue_id,repo_name,issue_number,title,body,state_final,author_login,agent_type,n_gharchive_events,comments_count_reported,...,reactions_laugh,reactions_hooray,reactions_confused,reactions_heart,reactions_rocket,reactions_eyes,n_labels,n_assignees,labels,n_comments_actual
1698,curtisdelicata/genealogy-laravel#1,curtisdelicata/genealogy-laravel,1,Sweep: improve codebase for laravel 11 and ref...,### Details\n\n_No response_,open,curtisdelicata,Sweep,1,NaN,...,0,0,0,0,0,0,0,0,NaN,0
2631,liberu-crm/crm-laravel#37,liberu-crm/crm-laravel,37,Sweep: finish crm features,### Details\n\nFinish the required features fo...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
2633,liberu-genealogy/.github#2,liberu-genealogy/.github,2,Sweep: improve design,### Details\n\nImprove blade files for layout ...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
2634,liberu-social-network/social-network-laravel#5,liberu-social-network/social-network-laravel,5,Sweep: database schema,### Details\n\n# Database Schema for Social Ne...,closed,curtisdelicata,Sweep,4,NaN,...,0,0,0,0,0,1,0,2,NaN,0
2635,liberusoftware/boilerplate-laravel#70,liberusoftware/boilerplate-laravel,70,Sweep: Run php artisan db:seed INFO Seedi...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
2637,liberusoftware/genealogy-laravel#1,liberusoftware/genealogy-laravel,1,Sweep: improve codebase for laravel 11 and ref...,### Details\n\n_No response_,open,curtisdelicata,Sweep,1,NaN,...,0,0,0,0,0,0,2,0,dependencies;javascript,1
4041,liberu-genealogy/genealogy-laravel#441,liberu-genealogy/genealogy-laravel,441,Sweep: add logo to home-navbar component. Logo...,\n\n\n<details open>\n<summary>Checklist</summ...,closed,curtisdelicata,Sweep,1,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4135,liberu-genealogy/genealogy-laravel#764,liberu-genealogy/genealogy-laravel,764,Sweep: create database liberu inside the insta...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,1,0,0,1,1,0,sweep,1
4155,liberu-genealogy/genealogy-laravel#613,liberu-genealogy/genealogy-laravel,613,Sweep: jetstream login,### Details\n\nReplace Filament login page wit...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,1,0,1,1,1,0,sweep,1
4173,liberu-genealogy/laravel-gramps-xml#10,liberu-genealogy/laravel-gramps-xml,10,Sweep: merge app/ into src/,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4221,liberu-genealogy/genealogy-laravel#480,liberu-genealogy/genealogy-laravel,480,Sweep: change button nav links in resources/vi...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,0,1,1,0,sweep,2
4511,liberu-genealogy/php-dna#129,liberu-genealogy/php-dna,129,Sweep: improve gd,### Details\n\nImprove and add php GD image li...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,0
4522,liberu-genealogy/genealogy-laravel#333,liberu-genealogy/genealogy-laravel,333,Sweep: static,### Details\n\n Cannot make non static method...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4553,liberu-genealogy/genealogy-laravel#168,liberu-genealogy/genealogy-laravel,168,Sweep: fix syntax errors on the file app/Model...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,0,1,1,0,sweep,1
4558,liberu-genealogy/genealogy-laravel#134,liberu-genealogy/genealogy-laravel,134,Sweep: correctly place use imports,### Details\n\nBug. Correctly place use import...,open,curtisdelicata,Sweep,1,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4568,liberu-real-estate/real-estate-laravel#53,liberu-real-estate/real-estate-laravel,53,Sweep: home page,### Details\n\nCreate a responsive home page l...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,0
4569,liberu-genealogy/genealogy-laravel#475,liberu-genealogy/genealogy-laravel,475,Sweep: change button nav links in resources/vi...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,0,1,1,0,sweep,2
4570,liberu-genealogy/php-dna#147,liberu-genealogy/php-dna,147,Sweep: Sweep: Refactor Visualization.php and u...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4602,liberu-genealogy/genealogy-laravel#346,liberu-genealogy/genealogy-laravel,346,Sweep:,### Details\n\nwrite tests for:\r\n\r\napp/Fil...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4625,liberu-genealogy/genealogy-laravel#125,liberu-genealogy/genealogy-laravel,125,Sweep: add public home page,### Details\n\nCopy and convert from vue/vueti...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4643,liberu-genealogy/genealogy-laravel#612,liberu-genealogy/genealogy-laravel,612,Sweep: implementation of https://github.com/st...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,1,0,0,1,1,0,sweep,1
4721,liberu-genealogy/genealogy-laravel#656,liberu-genealogy/genealogy-laravel,656,Sweep: copy jetstream models,### Details\n\nCopy the files from https://git...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4735,liberu-genealogy/genealogy-laravel#750,liberu-genealogy/genealogy-laravel,750,Sweep: create new github workflow for testing ...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,4,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4737,liberu-genealogy/php-gedcom#11,liberu-genealogy/php-gedcom,11,Sweep: write full tests,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,0
4828,liberu-genealogy/genealogy-laravel#515,liberu-genealogy/genealogy-laravel,515,Sweep: make sure d'Aboville and Henry reports ...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,0,1,1,0,sweep,1
4831,liberu-genealogy/genealogy-laravel#91,liberu-genealogy/genealogy-laravel,91,Sweep: complete people resource,### Details\n\nComplete the filament 3 form an...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4861,liberu-genealogy/genealogy-laravel#300,liberu-genealogy/genealogy-laravel,300,Sweep: pedigree livewire fix,### Details\n\nFix pedigree chart page and upd...,open,curtisdelicata,Sweep,1,NaN,...,0,0,0,0,1,1,1,0,sweep,1
4931,liberu-genealogy/genealogy-laravel#166,liberu-genealogy/genealogy-laravel,166,Sweep: fix syntax errors on team model,### Details\n\nBug: fix syntax errors on the f...,closed,curtisdelicata,Sweep,2,NaN,...,0,0,0,0,0,1,1,0,sweep,1
4995,liberu-genealogy/genealogy-laravel#767,liberu-genealogy/genealogy-laravel,767,Sweep: add stripe support using laravel cashie...,### Details\n\n_No response_,closed,curtisdelicata,Sweep,2,NaN,...,0,0,1,0,0,1,1,0,sweep,1

In [13]:
df_issues.author_type.unique()

<StringArray>
['Bot', 'User']
Length: 2, dtype: str

In [14]:
df_issues['author_type'].value_counts()

author_type
User    2696
Bot     2304
Name: count, dtype: int64

In [15]:
df_issues.groupby('author_type')['agent_type'].value_counts()

author_type  agent_type
Bot          CodeRabbit            1665
             Devin                  473
             Claude_Code             60
             Amazon_Q                37
             SWE_agent               29
             Gemini_Code_Assist      17
             Sweep                   12
             Jules                    6
             Kiro                     4
             Aider                    1
User         Claude_Code            820
             Sweep                  684
             CodeRabbit             295
             SWE_agent              281
             Gemini_Code_Assist     240
             Devin                   74
             Amazon_Q                71
             Aider                   67
             Kiro                    60
             PR_Agent                55
             Jules                   43
             Copilot                  3
             Cursor                   3
Name: count, dtype: int64

In [18]:
df_issues.groupby('author_type')['state_final'].value_counts()

author_type  state_final
Bot          open           2205
             closed           99
User         open           1433
             closed         1263
Name: count, dtype: int64

In [16]:
df_issue_comments.head()

,comment_id,issue_id,issue_number,repo_name,body,author_login,agent_type,created_at
0,1873421835,mdtanrikulu/mhmdt.com#14,14,mdtanrikulu/mhmdt.com,"<div align='center'><a href=""https://github.co...",ironic-iterator[bot],Sweep,2024-01-01 18:04:06+00:00
1,1873582852,gwicho38/lsh#5,5,gwicho38/lsh,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-02 02:54:59+00:00
2,1874146523,xoo-creative/flash#48,48,xoo-creative/flash,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-02 15:08:25+00:00
3,1874732276,MrIbrahem/wd-core#62,62,MrIbrahem/wd-core,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-03 00:50:21+00:00
4,1874777672,jofftiquez/jofftiquez.dev#18,18,jofftiquez/jofftiquez.dev,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-03 02:28:14+00:00

In [17]:
df_issue_comments.shape

(1468, 8)

In [ ]:
df_issue_comments

In [43]:
df_issues.columns

Index(['issue_id', 'repo_name', 'issue_number', 'title', 'body', 'state_final',
       'author_login', 'agent_type', 'n_gharchive_events',
       'comments_count_reported', 'created_at', 'closed_at',
       'time_to_close_hours', 'html_url', 'api_state', 'state_reason',
       'locked', 'draft', 'is_pull_request', 'author_type', 'api_created_at',
       'api_updated_at', 'api_closed_at', 'comments_api', 'milestone_title',
       'milestone_state', 'reactions_total', 'reactions_plus_one',
       'reactions_minus_one', 'reactions_laugh', 'reactions_hooray',
       'reactions_confused', 'reactions_heart', 'reactions_rocket',
       'reactions_eyes', 'n_labels', 'n_assignees', 'labels',
       'n_comments_actual', 'title_length', 'body_length'],
      dtype='str')

In [44]:
df_issues[['issue_id', 'api_created_at', 'api_closed_at']]

,issue_id,api_created_at,api_closed_at
0,01capitain/jira-release-manager#66,2025-09-24 13:21:24+00:00,2025-10-12 13:47:53+00:00
1,01capitain/jira-release-manager#67,2025-09-24 13:32:47+00:00,2025-09-30 11:25:23+00:00
2,01fe23bcs183/indietix#102,2025-11-03 12:43:09+00:00,2025-11-03 13:06:02+00:00
3,01fe23bcs183/indietix#92,2025-11-03 12:42:23+00:00,NaT
4,01fe23bcs183/indietix#94,2025-11-03 12:42:28+00:00,NaT
...,...,...,...
4995,liberu-genealogy/genealogy-laravel#767,2024-06-08 19:28:27+00:00,2024-07-25 11:50:46+00:00
4996,JokerTrickster/board_game_app#28,2025-09-05 01:27:30+00:00,NaT
4997,davideast/jules-sdk-python#249,2026-03-10 18:25:24+00:00,2026-03-10 21:27:47+00:00
4998,aws/aws-toolkit-visual-studio#596,2026-04-09 08:03:29+00:00,NaT
4999,slopus/happy#165,2025-10-07 17:44:26+00:00,NaT

In [49]:
df_issues.dtypes

issue_id                                   str
repo_name                                  str
issue_number                             int64
title                                      str
body                                       str
state_final                                str
author_login                               str
agent_type                                 str
n_gharchive_events                       int64
comments_count_reported                float64
created_at                 datetime64[us, UTC]
closed_at                  datetime64[us, UTC]
time_to_close_hours                    float64
html_url                                   str
api_state                                  str
state_reason                               str
locked                                    bool
draft                                   object
is_pull_request                           bool
author_type                                str
api_created_at             datetime64[us, UTC]
api_updated_at             datetime64[us, UTC]
api_closed_at              datetime64[us, UTC]
comments_api                             int64
milestone_title                            str
milestone_state                            str
reactions_total                          int64
reactions_plus_one                       int64
reactions_minus_one                      int64
reactions_laugh                          int64
reactions_hooray                         int64
reactions_confused                       int64
reactions_heart                          int64
reactions_rocket                         int64
reactions_eyes                           int64
n_labels                                 int64
n_assignees                              int64
labels                                     str
n_comments_actual                        int64
title_length                             int64
body_length                            float64
dtype: object

In [50]:
df_issues.groupby('author_type')['is_pull_request'].value_counts()

author_type  is_pull_request
Bot          False              2297
             True                  7
User         False              2685
             True                 11
Name: count, dtype: int64

In [52]:
df_issues.groupby('author_type')['api_state'].value_counts()

author_type  api_state
Bot          closed       1293
             open         1011
User         closed       2016
             open          680
Name: count, dtype: int64

In [54]:
1293/(1293+1011), 2016/(2016+680)

(0.5611979166666666, 0.7477744807121661)

In [57]:
df_issues['close_duration'] = (df_issues['api_closed_at'] - df_issues['api_created_at']).dt.seconds

In [58]:
df_issues.groupby('author_type')['close_duration'].mean()

author_type
Bot     35353.117556
User    29276.183036
Name: close_duration, dtype: float64

In [59]:
df_issues.columns

Index(['issue_id', 'repo_name', 'issue_number', 'title', 'body', 'state_final',
       'author_login', 'agent_type', 'n_gharchive_events',
       'comments_count_reported', 'created_at', 'closed_at',
       'time_to_close_hours', 'html_url', 'api_state', 'state_reason',
       'locked', 'draft', 'is_pull_request', 'author_type', 'api_created_at',
       'api_updated_at', 'api_closed_at', 'comments_api', 'milestone_title',
       'milestone_state', 'reactions_total', 'reactions_plus_one',
       'reactions_minus_one', 'reactions_laugh', 'reactions_hooray',
       'reactions_confused', 'reactions_heart', 'reactions_rocket',
       'reactions_eyes', 'n_labels', 'n_assignees', 'labels',
       'n_comments_actual', 'title_length', 'body_length', 'close_duration'],
      dtype='str')

In [60]:
df_issues[['issue_id', 'comments_api','n_comments_actual']]

                                    issue_id  comments_api  n_comments_actual
0         01capitain/jira-release-manager#66             0                  0
1         01capitain/jira-release-manager#67             0                  0
2                  01fe23bcs183/indietix#102             1                  0
3                   01fe23bcs183/indietix#92             0                  0
4                   01fe23bcs183/indietix#94             0                  0
...                                      ...           ...                ...
4995  liberu-genealogy/genealogy-laravel#767             1                  1
4996        JokerTrickster/board_game_app#28             0                  0
4997          davideast/jules-sdk-python#249             1                  0
4998       aws/aws-toolkit-visual-studio#596             0                  0
4999                        slopus/happy#165             9                  0

[5000 rows x 3 columns]

In [ ]:
df_issues.groupby('author_type')['n_comments_actual'].mean()

author_type
Bot     0.141059
User    0.423961
Name: n_comments_actual, dtype: float64

In [63]:
df_issues.groupby('author_type')['n_labels'].mean()

author_type
Bot     0.607639
User    1.247774
Name: n_labels, dtype: float64

In [64]:
df_issues[['reactions_total', 'reactions_plus_one',
       'reactions_minus_one', 'reactions_laugh', 'reactions_hooray',
       'reactions_confused', 'reactions_heart', 'reactions_rocket',
       'reactions_eyes']].fillna(0, inplace=True)

/var/folders/lb/pqbkjwts485cwcl0v7sfts_40000gn/T/ipykernel_52034/3666682330.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  'reactions_eyes']].fillna(0, inplace=True)

,reactions_total,reactions_plus_one,reactions_minus_one,reactions_laugh,reactions_hooray,reactions_confused,reactions_heart,reactions_rocket,reactions_eyes
0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
4995,2,0,0,0,0,1,0,0,1
4996,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0
4998,0,0,0,0,0,0,0,0,0
4999,5,5,0,0,0,0,0,0,0

In [65]:
df_issues['total_reactions'] = df_issues[['reactions_total', 'reactions_plus_one',
       'reactions_minus_one', 'reactions_laugh', 'reactions_hooray',
       'reactions_confused', 'reactions_heart', 'reactions_rocket',
       'reactions_eyes']].sum(axis=1)

In [68]:
df_issues.groupby('author_type')['total_reactions'].mean()

author_type
Bot     0.092014
User    1.213650
Name: total_reactions, dtype: float64

In [69]:
df_issues['ym_created_at'] = df_issues['api_created_at'].dt.strftime("%Y%m")

In [76]:
check = df_issues.groupby("ym_created_at")['author_type'].value_counts().unstack().reset_index()
check['ym_created_at'] = check['ym_created_at'].astype(int)
check.sort_values(by='ym_created_at')

author_type  ym_created_at    Bot   User
0                   201903    NaN    1.0
1                   201910    NaN    1.0
2                   202107    NaN    1.0
3                   202201    NaN    2.0
4                   202203    NaN    1.0
5                   202204    NaN    1.0
6                   202303    NaN    1.0
7                   202304    NaN    1.0
8                   202305    NaN    1.0
9                   202306    NaN    1.0
10                  202307    NaN    3.0
11                  202308    1.0    9.0
12                  202309    NaN    8.0
13                  202310    NaN    6.0
14                  202311    NaN    5.0
15                  202312    NaN   11.0
16                  202401    9.0   84.0
17                  202402   17.0   81.0
18                  202403   21.0  107.0
19                  202404   17.0   84.0
20                  202405   36.0   68.0
21                  202406   17.0   45.0
22                  202407   13.0   38.0
23                  202408   23.0   27.0
24                  202409   49.0   16.0
25                  202410   54.0   26.0
26                  202411   80.0   20.0
27                  202412   68.0   26.0
28                  202501   85.0   20.0
29                  202502   77.0   22.0
30                  202503   52.0   34.0
31                  202504  111.0   37.0
32                  202505  111.0   45.0
33                  202506   89.0  101.0
34                  202507   90.0  170.0
35                  202508  178.0  176.0
36                  202509  116.0  111.0
37                  202510   73.0  121.0
38                  202511  120.0  154.0
39                  202512  157.0  163.0
40                  202601  184.0  214.0
41                  202602  179.0  264.0
42                  202603  168.0  226.0
43                  202604  108.0  158.0
44                  202605    1.0    2.0
45                  202606    NaN    1.0
46                  202607    NaN    2.0

In [78]:
df_issues[['api_created_at', 'created_at']].isnull().sum()

api_created_at    0
created_at        0
dtype: int64

In [80]:
df_issue_assignees.head()

                             issue_id assignee_login
0  01capitain/jira-release-manager#66     01capitain
1  01capitain/jira-release-manager#67     01capitain
2                      0xdln1/test#40    nbsriharsha
3                 1-blue/story-dict#8         1-blue
4                 1-blue/story-dict#9         1-blue

In [81]:
df_issue_assignees.shape

(2041, 2)

In [82]:
df_issue_assignees.issue_id.nunique()

1909

In [83]:
df_issue_assignees['issue_id'].value_counts()

issue_id
1c-syntax/antlr#39                        3
Sin-Estres-dev/Strezless#30               3
dearmoment-team/dear-moment-backend#55    3
xbmc4lyfe/nzbdavkodi#23                   3
A-1ro/audio-transcript-app#42             2
                                         ..
carlos-emr/carlos#265                     1
leynos/netsuke#98                         1
google-gemini/gemini-cli#19883            1
unclesp1d3r/CipherSwarm#639               1
stevenson-space/shs#398                   1
Name: count, Length: 1909, dtype: int64

In [84]:
df_issue_assignees[df_issue_assignees['issue_id'] == '1c-syntax/antlr#39']

             issue_id assignee_login
6  1c-syntax/antlr#39      nixel2007
7  1c-syntax/antlr#39    theshadowco
8  1c-syntax/antlr#39        Copilot

In [87]:
df_issues[df_issues['issue_id'] == '1c-syntax/antlr#39']

,issue_id,repo_name,issue_number,title,body,state_final,author_login,agent_type,n_gharchive_events,comments_count_reported,...,reactions_eyes,n_labels,n_assignees,labels,n_comments_actual,title_length,body_length,close_duration,total_reactions,ym_created_at
15,1c-syntax/antlr#39,1c-syntax/antlr,39,Нарушение инварианта класса RuleContext: paren...,## Описание проблемы\n\nВ классе `RuleContext`...,open,coderabbitai[bot],CodeRabbit,1,NaN,...,1,0,3,NaN,0,75,1862.0,NaN,2,202602

In [88]:
df_issues.columns

Index(['issue_id', 'repo_name', 'issue_number', 'title', 'body', 'state_final',
       'author_login', 'agent_type', 'n_gharchive_events',
       'comments_count_reported', 'created_at', 'closed_at',
       'time_to_close_hours', 'html_url', 'api_state', 'state_reason',
       'locked', 'draft', 'is_pull_request', 'author_type', 'api_created_at',
       'api_updated_at', 'api_closed_at', 'comments_api', 'milestone_title',
       'milestone_state', 'reactions_total', 'reactions_plus_one',
       'reactions_minus_one', 'reactions_laugh', 'reactions_hooray',
       'reactions_confused', 'reactions_heart', 'reactions_rocket',
       'reactions_eyes', 'n_labels', 'n_assignees', 'labels',
       'n_comments_actual', 'title_length', 'body_length', 'close_duration',
       'total_reactions', 'ym_created_at'],
      dtype='str')

In [89]:
df_issues[['issue_id', 'n_assignees']]

                                    issue_id  n_assignees
0         01capitain/jira-release-manager#66            1
1         01capitain/jira-release-manager#67            1
2                  01fe23bcs183/indietix#102            0
3                   01fe23bcs183/indietix#92            0
4                   01fe23bcs183/indietix#94            0
...                                      ...          ...
4995  liberu-genealogy/genealogy-laravel#767            0
4996        JokerTrickster/board_game_app#28            0
4997          davideast/jules-sdk-python#249            0
4998       aws/aws-toolkit-visual-studio#596            0
4999                        slopus/happy#165            0

[5000 rows x 2 columns]

In [90]:
df_issues.groupby('author_type')['n_assignees'].value_counts()

author_type  n_assignees
Bot          1              1357
             0               895
             2                51
             3                 1
User         0              2196
             1               424
             2                73
             3                 3
Name: count, dtype: int64

In [91]:
df_issues['author_type'].value_counts()

author_type
User    2696
Bot     2304
Name: count, dtype: int64

In [93]:
(1357+51+1)/2304

0.6115451388888888

In [95]:
df_issue_assignees[df_issue_assignees['assignee_login'].isin(df_issues['author_login'].unique())].shape

(457, 2)

In [98]:
df_issue_assignees[df_issue_assignees['assignee_login'].isin(df_issues['author_login'].unique())].assignee_login.nunique()

272

In [97]:
df_issue_assignees[df_issue_assignees['assignee_login'].isin(df_issues['author_login'].unique()) == False].shape

(1584, 2)

In [99]:
df_issue_assignees[df_issue_assignees['assignee_login'].isin(df_issues['author_login'].unique()) == False].assignee_login.nunique()

904

In [100]:
df_issue_comments.head()

,comment_id,issue_id,issue_number,repo_name,body,author_login,agent_type,created_at
0,1873421835,mdtanrikulu/mhmdt.com#14,14,mdtanrikulu/mhmdt.com,"<div align='center'><a href=""https://github.co...",ironic-iterator[bot],Sweep,2024-01-01 18:04:06+00:00
1,1873582852,gwicho38/lsh#5,5,gwicho38/lsh,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-02 02:54:59+00:00
2,1874146523,xoo-creative/flash#48,48,xoo-creative/flash,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-02 15:08:25+00:00
3,1874732276,MrIbrahem/wd-core#62,62,MrIbrahem/wd-core,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-03 00:50:21+00:00
4,1874777672,jofftiquez/jofftiquez.dev#18,18,jofftiquez/jofftiquez.dev,"<div align='center'><a href=""https://github.co...",sweep-ai[bot],Sweep,2024-01-03 02:28:14+00:00

In [102]:
df_lables.head()

                    issue_id  label
0  01fe23bcs183/indietix#102    bug
1   01fe23bcs183/indietix#92    bug
2   01fe23bcs183/indietix#94    bug
3      0x7o/SimpleBlogSite#2  sweep
4      0x7o/SimpleBlogSite#5  sweep

In [103]:
df_issues.columns

Index(['issue_id', 'repo_name', 'issue_number', 'title', 'body', 'state_final',
       'author_login', 'agent_type', 'n_gharchive_events',
       'comments_count_reported', 'created_at', 'closed_at',
       'time_to_close_hours', 'html_url', 'api_state', 'state_reason',
       'locked', 'draft', 'is_pull_request', 'author_type', 'api_created_at',
       'api_updated_at', 'api_closed_at', 'comments_api', 'milestone_title',
       'milestone_state', 'reactions_total', 'reactions_plus_one',
       'reactions_minus_one', 'reactions_laugh', 'reactions_hooray',
       'reactions_confused', 'reactions_heart', 'reactions_rocket',
       'reactions_eyes', 'n_labels', 'n_assignees', 'labels',
       'n_comments_actual', 'title_length', 'body_length', 'close_duration',
       'total_reactions', 'ym_created_at'],
      dtype='str')

In [104]:
df_issue_assignees.assignee_login.value_counts()

assignee_login
Copilot         149
leynos           44
JiayanL          23
JarbasAl         21
unclesp1d3r      18
               ...
Teebor-Choka      1
AnilMaktala       1
Tearran           1
aviralgarg05      1
joshuaf745        1
Name: count, Length: 1176, dtype: int64

In [107]:
df_issue_assignees[df_issue_assignees['assignee_login'].str.contains('bot')]

                                    issue_id  assignee_login
147       DostEducation/RP_IVR_analytics#482     thebelrobot
148       DostEducation/RP_IVR_analytics#483     thebelrobot
1767  PalisadoesFoundation/talawa-admin#5582  palisadoes-bot
1770  PalisadoesFoundation/talawa-admin#5666  palisadoes-bot
1775                   flyingrobots/gatos#66    flyingrobots
1793  PalisadoesFoundation/talawa-admin#5600  palisadoes-bot
1817                 rjmurillo/ai-agents#144   rjmurillo-bot
1828  PalisadoesFoundation/talawa-admin#5857  palisadoes-bot
1903  PalisadoesFoundation/talawa-admin#5626  palisadoes-bot
1928  PalisadoesFoundation/talawa-admin#5771  palisadoes-bot
1934  PalisadoesFoundation/talawa-admin#5655  palisadoes-bot
1995  PalisadoesFoundation/talawa-admin#5764  palisadoes-bot
2017                 rjmurillo/ai-agents#338   rjmurillo-bot